<?php

namespace AppBundle\Repository;

/**
 * UrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUnprocessed(){
        $qb = $this->createQueryBuilder('q');
        $qb->select('q.id, q.link')
        ->where('q.processed IS NULL OR q.processed = 0');

        return $qb->getQuery()
            ->getResult();
    }
}
